twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme: 'bootstrap_4_layout.html.twig'
    paths:
        './public/images': images


when@test:
    twig:
        strict_variables: true
